apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-test
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
      - name: jenkins-test
        image: ghcr.io/yourusername/jenkins-test:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-test
spec:
  selector:
    app: jenkins-test
  ports:
  - port: 80
    targetPort: 3000
  type: NodePort

